### ISSUE TITLE
Dockerfile fails during rake spec stage

### ISSUE THREAD

**Issue by brettporter** [rubys/whimsy-agenda#10]
During `rake spec` I get the following error in the docker build:

```
     Capybara::DriverNotFoundError:
       no driver called :poltergeist was found, available drivers: :rack_test, :selenium
```

:ghost:

**Comment by rubys** [comment]
I get that error too, so you have done nothing wrong.  I'm not sure when that stopped working.  The hope is that it starts working again when the new version of Phantom.js comes out "RSN": https://github.com/ariya/phantomjs/issues/12970
